=== bopopescu/pspec-sql/language/src/privacy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/privacy"
	xmlns:tns="http://www.example.org/privacy" elementFormDefault="qualified"
	attributeFormDefault="unqualified">

	<!-- Elements which have an identifier should be of this type -->
	<complexType name="identifiedObjectType">
		<attribute name="id" use="required" type="NCName"></attribute>
	</complexType>

	<!-- Elements which refer to an identifier should be of this type -->
	<complexType name="objectRefType">
		<attribute name="refid" use="required" type="NCName"></attribute>
	</complexType>

	<!-- Identified Elements which have descriptions should be of this type -->
	<complexType name="describedObjectType">
		<complexContent>
			<extension base="tns:identifiedObjectType">
				<sequence>
					<element name="short-description" minOccurs="0" maxOccurs="1"></element>
					<element name="long-description" minOccurs="0" maxOccurs="1"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<!-- Elements which can participate in a hierarchy should have this type -->
	<complexType name="hierarchicalType">
		<complexContent>
			<extension base="tns:describedObjectType">
				<attribute name="parent" use="optional" type="NCName"></attribute>
			</extension>
		</complexContent>
	</complexType>



	<!-- Contact information -->
	<complexType name="contactInfoType">
		<sequence>
			<element name="name" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="organization" type="string" minOccurs="1"
				maxOccurs="1"></element>
			<element name="e-mail" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="address" type="string" minOccurs="1"
				maxOccurs="1"></element>
			<element name="country" type="string" minOccurs="1"
				maxOccurs="1"></element>
		</sequence>
	</complexType>


	<!-- Information on a policy or a vocabulary -->
	<complexType name="infoType">
		<complexContent>
			<extension base="tns:describedObjectType">
				<sequence>
					<element name="issuer" minOccurs="0" maxOccurs="1"
						type="tns:contactInfoType"></element>
					<element name="location" minOccurs="0" maxOccurs="1" type="anyURI"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="desensitizeOpType">
		<sequence>
			<element name="UDF" type="NCName"></element>
			<element name="class" type="string"></element>
		</sequence>
	</complexType>

	<simpleType name="javaClassType">
		<restriction base="string">
			<pattern value="([a-zA-Z_$][a-zA-Z\d_$]*\.)*[a-zA-Z_$][a-zA-Z\d_$]*"></pattern>
		</restriction>
	</simpleType>


	<complexType name="userCategoryContainerType">
		<complexContent>
			<extension base="tns:describedObjectType">
				<sequence>
					<element name="user-category" minOccurs="0" maxOccurs="unbounded"
						type="tns:hierarchicalType"></element>
				</sequence>
				<attribute name="base" type="NCName"></attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="dataCategoryContainerType">
		<complexContent>
			<extension base="tns:describedObjectType">
				<sequence>
					<element name="data-category" minOccurs="0" maxOccurs="unbounded">
						<complexType>
							<complexContent>
								<extension base="tns:hierarchicalType">
									<sequence>
										<element name="desensitize-operation" type="tns:desensitizeOpType"
											minOccurs="0"></element>
									</sequence>
								</extension>
							</complexContent>
						</complexType>
					</element>
				</sequence>
				<attribute name="base" type="NCName"></attribute>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="dataCategoryRefType">
		<complexContent>
			<extension base="tns:objectRefType">
				<choice maxOccurs="unbounded">
					<element name="all"></element>
					<element name="select"></element>
					<element name="test"></element>
					<element name="equal-test"></element>
					<element name="range-test"></element>
					<element name="bounded-range-test"></element>
					<element name="unbounded-range-test"></element>
				</choice>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="dataAssociationType">
		<sequence>
			<element name="data-category-ref" type="tns:dataCategoryRefType"
				minOccurs="2" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="baseRulingType" abstract="true">
		<complexContent>
			<extension base="tns:describedObjectType">
				<sequence>
					<element name="user-category-ref" type="tns:objectRefType"
						minOccurs="1" maxOccurs="unbounded"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>



	<complexType name="rulingType">
		<complexContent>
			<extension base="tns:baseRulingType">
				<sequence>
					<element name="data-category-ref" type="tns:dataCategoryRefType"
						minOccurs="0" maxOccurs="unbounded"></element>
					<element name="data-association" type="tns:dataAssociationType"
						maxOccurs="unbounded"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="restrictOpType">
		<sequence>
			<element name="data-category-ref" type="tns:objectRefType"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="restrictType">
		<complexContent>
			<extension base="tns:baseRulingType">
				<sequence>
					<choice>
						<element name="data-category-ref" type="tns:dataCategoryRefType"></element>
						<element name="data-association" type="tns:dataAssociationType"></element>
					</choice>
					<element name="restriction">
						<complexType>
							<choice>
								<element name="desensitize" type="tns:restrictOpType"></element>
								<element name="aggregate" type="tns:restrictOpType"></element>
							</choice>
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<element name="vocabulary">
		<complexType>
			<sequence>
				<element name="vocabulary-information" minOccurs="1"
					maxOccurs="1" type="tns:infoType"></element>
				<element name="user-category-container" type="tns:userCategoryContainerType"
					minOccurs="0" maxOccurs="unbounded">

					<key name="user-category-identifier">
						<selector xpath="tns:user-category"></selector>
						<field xpath="@id"></field>
					</key>
				</element>
				<element name="data-category-container" type="tns:dataCategoryContainerType"
					minOccurs="0" maxOccurs="unbounded">
					<key name="data-category-identifier">
						<selector xpath="tns:data-category"></selector>
						<field xpath="@id"></field>
					</key>
				</element>
			</sequence>
			<attribute name="base" use="optional" type="anyURI"></attribute>
		</complexType>
	</element>




	<element name="privacy-policy">
		<complexType>
			<sequence>
				<element name="policy-information" minOccurs="1" maxOccurs="1"
					type="tns:infoType"></element>

				<element name="vocabulary-ref">
					<complexType>
						<sequence>
							<element name="user-category-container" type="tns:objectRefType"></element>
							<element name="data-category-container" type="tns:objectRefType"></element>
						</sequence>
						<attribute name="location" type="anyURI"></attribute>
					</complexType>
				</element>
				<element name="rules">
					<complexType>
						<sequence>
							<choice minOccurs="1" maxOccurs="unbounded">
								<element name="allow" type="tns:rulingType">
								</element>
								<element name="deny" type="tns:rulingType"></element>
								<element name="restrict" type="tns:restrictType"></element>
							</choice>
						</sequence>
					</complexType>
				</element>
			</sequence>

			<attribute name="default-ruling" use="required">
				<simpleType>
					<restriction base="string">
						<enumeration value="allow" />
						<enumeration value="deny" />
					</restriction>
				</simpleType>
			</attribute>
		</complexType>

		<!-- Rule id's must be unique within a policy -->
		<unique name="uniqueRuleId">
			<selector xpath="./tns:rule" />
			<field xpath="@id" />
		</unique>
	</element>


</schema>

=== bopopescu/pspec-sql/language_v2/intel/spark-vocab.xml
<?xml version="1.0" encoding="UTF-8"?>

<vocabulary base="intel/base-vocab.xml" xmlns="http://www.example.org/privacy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/privacy ../res/privacy.xsd">
	<vocabulary-information id="vocab-info">
		<issuer>
			<name>YanDong</name>
			<organization>Intel</organization>
			<e-mail>dong.yan@intel.com</e-mail>
			<address>IntelLabChina</address>
			<country>China</country>
		</issuer>
	</vocabulary-information>

	<data-category-container id="tpcds-data" base="default-data">
		<data-category id="address" parent="qi"></data-category>
		<data-category id="email" parent="qi"></data-category>
		<data-category id="login" parent="qi"></data-category>
		<data-category id="gender" parent="qi"></data-category>
		<data-category id="name" parent="qi"></data-category>
		<data-category id="birth" parent="qi"></data-category>
		<data-category id="education" parent="qi"></data-category>
		<data-category id="marital" parent="qi"></data-category>

		<data-category id="city" parent="address"></data-category>
		<data-category id="county" parent="address"></data-category>
		<data-category id="state" parent="address"></data-category>
		<data-category id="country" parent="address"></data-category>
		<data-category id="gmt" parent="address"></data-category>
		<data-category id="suite" parent="address"></data-category>
		<data-category id="zip" parent="address">
			<desensitize-operations>
				<operation>truncate</operation>
			</desensitize-operations>
		</data-category>
		<data-category id="location_type" parent="address"></data-category>
		<data-category id="street" parent="address"></data-category>

		<data-category id="street_number" parent="street"></data-category>
		<data-category id="street_name" parent="street"></data-category>
		<data-category id="street_type" parent="street"></data-category>

		<data-category id="nick_name" parent="name"></data-category>
		<data-category id="first_name" parent="name"></data-category>
		<data-category id="last_name" parent="name"></data-category>

		<data-category id="birth_date" parent="birth"></data-category>
		<data-category id="birth_country" parent="birth"></data-category>

		<data-category id="birth_day" parent="birth_date"></data-category>
		<data-category id="birth_month" parent="birth_date"></data-category>
		<data-category id="birth_year" parent="birth_date"></data-category>

		<data-category id="dep" parent="sa"></data-category>
		<data-category id="financial" parent="sa">
			<desensitize-operations>
				<operation>sum</operation>
				<operation>avg</operation>
			</desensitize-operations>
		</data-category>
		<data-category id="vehicle" parent="sa"></data-category>
		<data-category id="buy_potential" parent="sa"></data-category>
		<data-category id="credit_rating" parent="sa"></data-category>
	</data-category-container>
</vocabulary>

=== bopopescu/pspec-sql/language/src/example-policy.xml
<?xml version="1.0" encoding="UTF-8"?>

<privacy-policy default-ruling="allow"
	xmlns="http://www.example.org/privacy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/privacy privacy.xsd">
	<policy-information id="school-policy">
		<issuer>
			<name>luochen</name>
			<organization>Tsinghua</organization>
			<e-mail>luochen01@vip.qq.com</e-mail>
			<address>Tsinghua</address>
			<country>China</country>
		</issuer>
	</policy-information>
	
	<vocabulary-ref base="example-vocabulary.xml">
		<user-categories ref="school-users"/>
		<data-categories ref="school-data" />
	</vocabulary-ref>
	<rules>
		<allow id="allow-teacher-gpa">
			<user-category refid="teacher"/>
			<action>
				<all/>
			</action>
			<data-association>
				<data-category refid="student-id"/>
				<data-category refid="gpa"/>
			</data-association>
		</allow>
		
		<restrict id="restrict-gpa">
			<user-category refid="employee"/>
			<action>
				<select/>
				<equal-test/>
			</action>
			<data-association>
				<data-category refid="student-id"/>
				<data-category refid="gpa"/>
			</data-association>
			<restriction>
				<desensitize>
					<data-category refid="gpa"/>
				</desensitize>
			</restriction>
		</restrict>
	</rules>
	
	
</privacy-policy>

=== bopopescu/pspec-sql/language_v2/tpc-ds/store_policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<privacy-policy xmlns="http://www.example.org/privacy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/privacy privacy.xsd">
	<policy-information id="store-policy">
		<issuer>
			<name>luochen</name>
			<organization>Tsinghua</organization>
			<e-mail>luochen01@vip.qq.com</e-mail>
			<address>Tsinghua</address>
			<country>China</country>
		</issuer>
	</policy-information>
	<vocabulary-ref location="tpc-ds/store_policy">
		<user-category-container refid="default-user" />
		<data-category-container refid="store-data" />
	</vocabulary-ref>
	<rules>
		<rule id="forbid_project">
			<user-category refid="app"></user-category>
			<data-category refid="ka" action="project"></data-category>
			<data-category refid="name" action="project"></data-category>
			<data-category refid="customer_suite" action="project"></data-category>
			<data-category refid="customer_sa" action="project"></data-category>
			<restriction>
				<forbid></forbid>
			</restriction>
		</rule>

		<rule id="forbid_name_customer_sa">
			<user-category refid="app"></user-category>
			<data-association>
				<data-category refid="name"></data-category>
				<data-category refid="customer_sa"></data-category>
			</data-association>
			<restriction>
				<forbid></forbid>
			</restriction>
		</rule>

		<rule id="forbid_ka_customer_sa">
			<user-category refid="app"></user-category>
			<data-association>
				<data-category refid="ka"></data-category>
				<data-category refid="customer_sa"></data-category>
			</data-association>
			<restriction>
				<forbid></forbid>
			</restriction>
		</rule>

		<rule id="forbid_ka_qi_project">
			<user-category refid="app"></user-category>
			<data-association>
				<data-category refid="ka"></data-category>
				<data-category refid="qi" action="project"></data-category>
			</data-association>
			<restriction>
				<forbid></forbid>
			</restriction>
		</rule>


		<rule id="truncate_customer_zip">
			<user-category refid="app"></user-category>
			<data-category refid="customer_zip"></data-category>
			<restriction>
				<desensitize>
					<UDF>truncate</UDF>
				</desensitize>
			</restriction>
		</rule>

		<rule id="substr_customer_suite">
			<user-category refid="app"></user-category>
			<data-category refid="customer_suite"></data-category>
			<restriction>
				<desensitize>
					<UDF>substr</UDF>
				</desensitize>
			</restriction>
		</rule>
		
		<rule id="agg_financial">
			<user-category refid="app"></user-category>
			<data-category refid="financial"></data-category>
			<restriction>
				<desensitize>
					<UDF>sum</UDF>
					<UDF>avg</UDF>
				</desensitize>
			</restriction>
		</rule>


	</rules>
</privacy-policy>

=== bopopescu/pspec-sql/language/test/example-policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<privacy-policy default-ruling="allow"
	xmlns="http://www.example.org/privacy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/privacy ../src/privacy.xsd">
	<policy-information id="school-policy">
		<issuer>
			<name>luochen</name>
			<organization>Tsinghua</organization>
			<e-mail>luochen01@vip.qq.com</e-mail>
			<address>Tsinghua</address>
			<country>China</country>
		</issuer>
	</policy-information>
	
	<vocabulary-ref location="test/example-vocabulary.xml">
		<user-category-container refid="school-users"/>
		<data-category-container refid="school-data" />
	</vocabulary-ref>
	<rules>
		<allow id="allow-all">
			<user-category-ref refid="employee"/>
			<data-category-ref refid="pii" action="all"/>
		</allow>
		<deny id="deny-name-phone">
			<user-category-ref refid="employee"/>
			<data-category-ref refid="contact"/>
		</deny>
		<deny id="deny-disease">
			<user-category-ref refid="employee"/>
			<data-association>
				<data-category-ref refid="phone"/>
				<data-category-ref refid="disease"/>
			</data-association>
		</deny>
	</rules>
</privacy-policy>

=== bopopescu/pspec-sql/language/test/example-vocabulary.xml
<?xml version="1.0" encoding="UTF-8"?>

<vocabulary base="test/base-vocabulary.xml"
	xmlns="http://www.example.org/privacy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/privacy ../src/privacy.xsd">
	
	<vocabulary-information id="vocab-info">
		<issuer>
			<name>luochen</name>
			<organization>Tsinghua</organization>
			<e-mail>luochen01@vip.qq.com</e-mail>
			<address>Tsinghua</address>
			<country>China</country>
		</issuer>
	</vocabulary-information>
	
	<user-category-container id="school-users" base="default-users">
		<user-category id="student" parent="employee"/>
		<user-category id="teacher" parent="employee"/>
	</user-category-container>
	
	
	<data-category-container id="school-data">
		<data-category id="all"/>
		<data-category id="pii" parent="all"/>
		<data-category id="health" parent="all"/>
		<data-category id="financial" parent="all"/>
		<data-category id="name" parent="pii"/>
		<data-category id="ssn" parent="pii"/>
		<data-category id="contact" parent="pii"/>
		<data-category id="phone" parent="contact"/>
		<data-category id="email" parent="contact"/>
		<data-category id="disease" parent="health"/>
		<data-category id="health-test" parent="health"/>
		<data-category id="income" parent="financial"/>
		<data-category id="tax" parent="financial"/>
		<data-category id="salary" parent="tax"/>
	</data-category-container>
</vocabulary>
